//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartID { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual User User { get; set; }
    }
}
